# Generated by Django 3.1.4 on 2021-01-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=20, verbose_name='管理员用户')),
                ('inner_ip', models.GenericIPAddressField(verbose_name='内网IP')),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP')),
                ('hostname', models.CharField(max_length=30, verbose_name='主机名')),
                ('docker_port', models.IntegerField(verbose_name='远程端口')),
                ('root_ssh', models.BooleanField(default=True, verbose_name='是否允许 root 远程')),
                ('use_type', models.PositiveSmallIntegerField(choices=[(1, 'DL服务器'), (2, 'SF服务器'), (3, 'WDS服务器')], default=1, verbose_name='用途')),
                ('quanta_project', models.CharField(max_length=50, verbose_name='广达机种名')),
                ('google_project', models.CharField(max_length=50, verbose_name='google机种名')),
                ('hp_project', models.CharField(max_length=50, verbose_name='HP机种名')),
                ('admin_user', models.CharField(max_length=20, verbose_name='管理员用户')),
                ('admin_pass', models.CharField(max_length=50, verbose_name='管理员密码')),
                ('engine_manager', models.CharField(max_length=50, verbose_name='负责人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_user', models.CharField(max_length=50, verbose_name='修改人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('host_port_status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '停用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
    ]
